# Generated by Django 2.2.4 on 2021-09-06 19:26

from django.db import migrations
import phonenumbers


def format_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_obj = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone_obj):
            flat.owners_phonenumber_formatted = phonenumbers.format_number(
                phone_obj,
                phonenumbers.PhoneNumberFormat.E164
            )
            flat.save()


def move_backword(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_phonenumber_formatted = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20210906_2225'),
    ]

    operations = [
        migrations.RunPython(format_phone)
    ]
