# Generated by Django 2.2.4 on 2021-11-28 23:26

from django.db import migrations


def transfer_data(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owners_phonenumber_formatted=flat.owners_phonenumber_formatted
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [


    ]
